from __future__ import annotations
"""
StayVise — SQLAlchemy ORM Models
=================================
Tables
------
  users               Phone-first users (freelancers & clients)
  projects            Escrow projects linking a freelancer ↔ client
  milestones          Deliverable chunks inside a project
  trust_scores        Rolling trust metric per user (1-to-1 with users)
  disputes            Conflict records tied to a project/milestone
  transactions        Immutable financial ledger entries
  notifications       Outbound message log (email / push)

Design notes
------------
- All PKs: UUID generated by Postgres (gen_random_uuid())
- Timestamps: server-side via func.now(); updated_at uses onupdate
- Enums: Python Enum + SQLAlchemy Enum(native_enum=False) → stored as VARCHAR
- JSONB / ARRAY: backend-specific types (PostgreSQL only)
- Relationships: lazy="selectin" so async code never hits lazy-load errors
- Milestone sum == project total_amount is enforced in the service layer
  (cannot be done as a pure DB CHECK without a subquery, which is DDL-version-
  specific; a DB trigger is an alternative documented in infra/postgres/triggers.sql)
"""


import enum
from datetime import date, datetime
from decimal import Decimal
from typing import Optional, Any
from cryptography.fernet import Fernet

import sqlalchemy as sa
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.db.compat import GUID, JSONType, ArrayOfText

# ── Encryption Helper ──────────────────────────────────────────────────────────
def _get_fernet() -> Fernet:
    from app.core.config import settings
    # Ensure key is 32-byte base64 encoded
    return Fernet(settings.ENCRYPTION_KEY.encode())


# ══════════════════════════════════════════════════════════════════════════════
# Base & Mixin
# ══════════════════════════════════════════════════════════════════════════════


class Base(DeclarativeBase):
    """Shared declarative base — import this into alembic/env.py."""
    pass


class TimestampMixin:
    """
    Adds created_at / updated_at columns to any model.
    Both are set server-side so they are always in UTC even if the app
    server is in a different timezone.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


# ══════════════════════════════════════════════════════════════════════════════
# Enums
# ══════════════════════════════════════════════════════════════════════════════


class UserRole(str, enum.Enum):
    freelancer = "freelancer"
    client = "client"
    admin = "admin"


class ProjectStatus(str, enum.Enum):
    draft = "draft"
    open = "open"
    awaiting_payment = "awaiting_payment"
    in_progress = "in_progress"
    completed = "completed"
    disputed = "disputed"
    cancelled = "cancelled"


class MilestoneStatus(str, enum.Enum):
    pending = "pending"
    submitted = "submitted"
    approved = "approved"
    disputed = "disputed"
    released = "released"


class DisputeStatus(str, enum.Enum):
    open = "open"
    under_review = "under_review"
    resolved_freelancer = "resolved_freelancer"
    resolved_client = "resolved_client"
    resolved = "resolved"
    escalated = "escalated"


class TransactionType(str, enum.Enum):
    escrow_hold = "escrow_hold"
    milestone_release = "milestone_release"
    platform_fee = "platform_fee"
    refund = "refund"


class TransactionStatus(str, enum.Enum):
    pending = "pending"
    success = "success"
    failed = "failed"


class NotificationType(str, enum.Enum):
    project_created = "project_created"
    payment_received = "payment_received"
    milestone_submitted = "milestone_submitted"
    milestone_approved = "milestone_approved"
    dispute_opened = "dispute_opened"
    auto_release_warning = "auto_release_warning"


class NotificationChannel(str, enum.Enum):
    email = "email"
    push = "push"


class SubmissionType(str, enum.Enum):
    contact = "contact"
    career = "career"
    general = "general"


# ══════════════════════════════════════════════════════════════════════════════
# Helper: SA Enum factory
# ══════════════════════════════════════════════════════════════════════════════


def _sa_enum(enum_class: type[enum.Enum], **kwargs) -> "SAEnum":  # type: ignore[name-defined]
    """Create a SQLAlchemy Enum that stores values as VARCHAR (not native PG enum)."""
    from sqlalchemy import Enum as SAEnum  # local import to avoid circular at module level
    return SAEnum(
        enum_class,
        native_enum=False,
        length=64,
        **kwargs,
    )


from sqlalchemy import Enum as SAEnum  # noqa: E402 — used in mapped_column defaults


# ══════════════════════════════════════════════════════════════════════════════
# 1. users
# ══════════════════════════════════════════════════════════════════════════════


class User(TimestampMixin, Base):
    """
    A StayVise user — onboarded via verified email and phone number.
    Password is nullable because auth is secure-link first; password may be
    set later for dashboard access.
    """

    __tablename__ = "users"
    __table_args__ = (
        Index(
            "uq_razorpay_fund_account",
            "razorpay_fund_account_id",
            unique=True,
            postgresql_where=text("razorpay_fund_account_id IS NOT NULL"),
        ),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    unique_id: Mapped[str] = mapped_column(
        String(20),
        unique=True,
        nullable=False,
        index=True,
        default=lambda: f"SV-{__import__('secrets').token_hex(4).upper()}",
        comment="Short unique ID for admins and user profiles (e.g. SV-1A2B3C4D)",
    )
    phone_number: Mapped[Optional[str]] = mapped_column(
        String(20),
        unique=True,
        nullable=True,
        index=True,
        comment="E.164 format, e.g. +919876543210. Null for magic link users until verified.",
    )
    messenger_name: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="Profile name from the messaging platform (Meta)",
    )
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    email: Mapped[Optional[str]] = mapped_column(
        String(255), unique=True, nullable=True, index=True
    )
    username: Mapped[Optional[str]] = mapped_column(
        String(50),
        unique=True,
        nullable=True,
        index=True,
        comment="Public vanity URL slug, e.g. stayvise.in/p/username",
    )
    bio: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Short biography / What I do (Markdown supported)",
    )
    avatar_url: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Profile photo URL or local data URI for dashboard/public profile",
    )
    password_hash: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="bcrypt hash; NULL for OTP-only users",
    )
    role: Mapped[UserRole] = mapped_column(
        SAEnum(UserRole, native_enum=False, length=20),
        nullable=False,
        default=UserRole.freelancer,
    )
    is_verified: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    onboarding_complete: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )

    # ── Preferences & Billing ─────────────────────────────────────────────────
    notification_prefs: Mapped[dict] = mapped_column(
        JSONType(),
        nullable=False,
        server_default=text("'{}'::jsonb"),
        comment="JSON record of notification toggles",
    )
    billing_plan: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default=text("'free'"),
        comment="'free' or 'pro'",
    )
    payout_details: Mapped[dict] = mapped_column(
        JSONType(),
        nullable=False,
        server_default=text("'{}'::jsonb"),
        comment="Masked payout configuration shown in dashboard settings",
    )
    subscription_expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Razorpay (for payouts) ────────────────────────────────────────────────
    razorpay_contact_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True,
        comment="RazorpayX Contact ID for this user",
    )
    razorpay_fund_account_id: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="RazorpayX Fund Account ID (bank/UPI) for payouts",
    )
    razorpay_subscription_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True,
        comment="Razorpay Subscription ID for Pro plan billing",
    )

    # ── Sensitive Data (Encrypted) ──────────────────────────────────────────
    _bank_account_number: Mapped[Optional[str]] = mapped_column(
        "bank_account_number", Text, nullable=True
    )

    @property
    def bank_account_number(self) -> Optional[str]:
        if not self._bank_account_number:
            return None
        return _get_fernet().decrypt(self._bank_account_number.encode()).decode()

    @bank_account_number.setter
    def bank_account_number(self, value: str) -> None:
        self._bank_account_number = _get_fernet().encrypt(value.encode()).decode()

    # ── Relationships ──────────────────────────────────────────────────────────
    trust_score: Mapped[Optional["TrustScore"]] = relationship(
        "TrustScore", back_populates="user", uselist=False, lazy="selectin", cascade="all, delete-orphan", passive_deletes=True
    )
    freelancer_projects: Mapped[list["Project"]] = relationship(
        "Project",
        foreign_keys="Project.freelancer_id",
        back_populates="freelancer",
        lazy="selectin",
    )
    client_projects: Mapped[list["Project"]] = relationship(
        "Project",
        foreign_keys="Project.client_id",
        back_populates="client",
        lazy="selectin",
    )
    raised_disputes: Mapped[list["Dispute"]] = relationship(
        "Dispute",
        foreign_keys="Dispute.raised_by_id",
        back_populates="raised_by",
        lazy="selectin",
    )
    resolved_disputes: Mapped[list["Dispute"]] = relationship(
        "Dispute",
        foreign_keys="Dispute.resolved_by_id",
        back_populates="resolved_by",
        lazy="selectin",
    )
    notifications: Mapped[list["Notification"]] = relationship(
        "Notification", back_populates="user", lazy="selectin", cascade="all, delete-orphan", passive_deletes=True
    )
    app_sessions: Mapped[list["UserSession"]] = relationship(
        "UserSession", back_populates="user", lazy="selectin", cascade="all, delete-orphan", passive_deletes=True
    )

    @property
    def active_sessions_count(self) -> int:
        return sum(1 for s in self.app_sessions if s.is_active)

    def __repr__(self) -> str:
        return (
            f"<User id={self.id!r} phone={self.phone_number!r} "
            f"role={self.role.value!r}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# Marketplace Proposals
# ══════════════════════════════════════════════════════════════════════════════


class Proposal(TimestampMixin, Base):
    """
    Freelancer's bid/application for a public project.
    """

    __tablename__ = "proposals"
    __table_args__ = (
        UniqueConstraint("project_id", "freelancer_id", name="uq_proposals_project_freelancer"),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    project_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    freelancer_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    amount: Mapped[int] = mapped_column(sa.BigInteger, nullable=False, comment="In paise")
    cover_letter: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default=text("'pending'")
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    project: Mapped["Project"] = relationship("Project", back_populates="proposals", lazy="selectin")
    freelancer: Mapped["User"] = relationship("User", lazy="selectin")

    def __repr__(self) -> str:
        return (
            f"<Proposal project={self.project_id!r} freelancer={self.freelancer_id!r} "
            f"amount={self.amount} status={self.status}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# Dashboard Sessions
# ══════════════════════════════════════════════════════════════════════════════


class UserSession(TimestampMixin, Base):
    """
    Track active web dashboard logins.
    Used for the 'Active Sessions' list in Security settings.
    """

    __tablename__ = "user_sessions"

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    user_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        comment="Opaque identifier mapping to JWT jti or random ID",
    )
    device_info: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    ip_address: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    location: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    last_active_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )

    user: Mapped["User"] = relationship("User", back_populates="app_sessions", lazy="selectin")


class MessengerSession(TimestampMixin, Base):
    """
    Persisted conversation state for StayVise Messenger (Meta API).
    Each record represents an active or expired chat session.
    """

    __tablename__ = "messenger_sessions"

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    phone_number: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
        comment="E.164 format of the user",
    )
    user_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    session_state: Mapped[dict] = mapped_column(
        JSONType(),
        nullable=False,
        server_default=text("'{}'::jsonb"),
        comment="State machine JSON: {'state': '...', 'data': {...}}",
    )
    last_message_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    user: Mapped[Optional["User"]] = relationship("User", lazy="selectin")



# ══════════════════════════════════════════════════════════════════════════════
# 2. projects
# ══════════════════════════════════════════════════════════════════════════════


class Project(TimestampMixin, Base):
    """
    An escrow project between one freelancer and one client.

    Financial invariant (enforced in service layer):
        total_amount == sum(milestones.amount)
        platform_fee_amount == total_amount * settings.ESCROW_FEE_PERCENT / 100
        freelancer_payout_amount == total_amount - platform_fee_amount
    """

    __tablename__ = "projects"
    __table_args__ = (
        # Fast lookup: all projects for a freelancer filtered by status
        Index("ix_projects_freelancer_status", "freelancer_id", "status"),
        # Fast lookup: all projects for a client filtered by status
        Index("ix_projects_client_status", "client_id", "status"),
        CheckConstraint(
            "total_amount > 0",
            name="chk_positive_amount",
        ),
        CheckConstraint(
            "platform_fee_amount >= 0",
            name="ck_projects_non_negative_fee",
        ),
        CheckConstraint(
            "freelancer_id != client_id",
            name="chk_no_self_deal",
        ),
        CheckConstraint(
            "deadline IS NULL OR deadline > (created_at AT TIME ZONE 'UTC')::date",
            name="chk_deadline_future",
        ),
        Index(
            "idx_projects_active",
            "freelancer_id",
            "updated_at",
            postgresql_where=text("status NOT IN ('completed', 'cancelled')"),
        ),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    freelancer_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=True,
    )
    client_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )

    status: Mapped[ProjectStatus] = mapped_column(
        SAEnum(ProjectStatus, native_enum=False, length=30),
        nullable=False,
        default=ProjectStatus.draft,
        index=True,
    )
    is_public: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )

    total_amount: Mapped[int] = mapped_column(
        sa.BigInteger, nullable=False, comment="In paise."
    )
    platform_fee_amount: Mapped[int] = mapped_column(sa.BigInteger, nullable=False)
    freelancer_payout_amount: Mapped[int] = mapped_column(sa.BigInteger, nullable=False)
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False, server_default=text("'INR'")
    )

    razorpay_order_id: Mapped[Optional[str]] = mapped_column(
        String(100), unique=True, nullable=True, index=True
    )
    razorpay_payment_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True
    )
    escrow_held_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    deadline: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    auto_release_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Set when last milestone submitted; funds release if client silent",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    freelancer: Mapped["User"] = relationship(
        "User", foreign_keys=[freelancer_id], back_populates="freelancer_projects", lazy="selectin"
    )
    client: Mapped["User"] = relationship(
        "User", foreign_keys=[client_id], back_populates="client_projects", lazy="selectin"
    )
    milestones: Mapped[list["Milestone"]] = relationship(
        "Milestone",
        back_populates="project",
        cascade="all, delete-orphan",
        order_by="Milestone.sequence_number",
        lazy="selectin",
    )
    disputes: Mapped[list["Dispute"]] = relationship(
        "Dispute", back_populates="project", lazy="selectin"
    )
    transactions: Mapped[list["Transaction"]] = relationship(
        "Transaction", back_populates="project", lazy="selectin"
    )
    proposals: Mapped[list["Proposal"]] = relationship(
        "Proposal", back_populates="project", cascade="all, delete-orphan", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Project id={self.id!r} title={self.title!r} "
            f"status={self.status.value!r} amount={self.total_amount}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# 3. milestones
# ══════════════════════════════════════════════════════════════════════════════


class Milestone(TimestampMixin, Base):
    """
    A deliverable unit within a project.

    Invariant (service layer):
        project.total_amount == SUM(milestone.amount for milestone in project.milestones)

    sequence_number is 1-indexed and determines the order milestones must be
    completed in (sequential release model).
    """

    __tablename__ = "milestones"
    __table_args__ = (
        # Unique ordering within a project
        UniqueConstraint("project_id", "sequence_number", name="uq_milestone_project_seq"),
        # Fast sorted fetch of milestones for a project
        Index("ix_milestones_project_sequence", "project_id", "sequence_number"),
        CheckConstraint("amount > 0", name="chk_positive_milestone"),
        CheckConstraint("sequence_number > 0", name="chk_seq_positive"),
        Index(
            "idx_pending_auto_release",
            "auto_release_at",
            postgresql_where=text("status = 'submitted'"),
        ),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    project_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    amount: Mapped[int] = mapped_column(sa.BigInteger, nullable=False, comment="In paise")
    sequence_number: Mapped[int] = mapped_column(Integer, nullable=False)

    status: Mapped[MilestoneStatus] = mapped_column(
        SAEnum(MilestoneStatus, native_enum=False, length=20),
        nullable=False,
        default=MilestoneStatus.pending,
        index=True,
    )

    submitted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    released_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    auto_release_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Funds release automatically after N days if client silent",
    )
    razorpay_payout_id: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True, comment="Razorpay Payout ID after funds released"
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    project: Mapped["Project"] = relationship(
        "Project", back_populates="milestones", lazy="selectin"
    )
    disputes: Mapped[list["Dispute"]] = relationship(
        "Dispute", back_populates="milestone", lazy="selectin"
    )
    transactions: Mapped[list["Transaction"]] = relationship(
        "Transaction", back_populates="milestone", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Milestone id={self.id!r} seq={self.sequence_number} "
            f"title={self.title!r} status={self.status.value!r} amount={self.amount}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# 4. trust_scores
# ══════════════════════════════════════════════════════════════════════════════


class TrustScore(TimestampMixin, Base):
    """
    Rolling trust metric for each user.
    Recalculated asynchronously by a Celery task after project state changes.

    score range: 0.00 – 100.00
    response_rate range: 0.00 – 100.00 (percentage)
    """

    __tablename__ = "trust_scores"
    __table_args__ = (
        CheckConstraint("score >= 0 AND score <= 100", name="chk_score_range"),
        CheckConstraint(
            "response_rate >= 0 AND response_rate <= 100",
            name="ck_trust_response_rate_range",
        ),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    user_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )

    score: Mapped[Decimal] = mapped_column(
        Numeric(5, 2), nullable=False, server_default=text("0")
    )
    total_projects: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    completed_projects: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    disputed_projects: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    avg_delivery_days: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(6, 2),
        nullable=True,
        comment="Average days from project start to completion",
    )
    response_rate: Mapped[Decimal] = mapped_column(
        Numeric(5, 2),
        nullable=False,
        server_default=text("100"),
        comment="% of project communications responded to within 24h",
    )
    last_calculated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    admin_override_score: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 2),
        nullable=True,
        comment="If set, overrides the calculated score",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship(
        "User", back_populates="trust_score", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<TrustScore user_id={self.user_id!r} score={self.score} "
            f"projects={self.total_projects}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# 5. disputes
# ══════════════════════════════════════════════════════════════════════════════


class Dispute(TimestampMixin, Base):
    """
    Raised by either party when milestone work is contested.
    evidence_urls is a Postgres ARRAY of TEXT (S3/Cloudflare R2 URLs).
    """

    __tablename__ = "disputes"
    __table_args__ = (
        Index("ix_disputes_project_status", "project_id", "status"),
        Index(
            "idx_disputes_open",
            "created_at",
            postgresql_where=text("status = 'open'"),
        ),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    project_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("projects.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    milestone_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("milestones.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    raised_by_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )

    status: Mapped[DisputeStatus] = mapped_column(
        SAEnum(DisputeStatus, native_enum=False, length=30),
        nullable=False,
        default=DisputeStatus.open,
        index=True,
    )
    reason: Mapped[str] = mapped_column(Text, nullable=False)
    details: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, server_default=text("'green'"))
    evidence_urls: Mapped[list[str]] = mapped_column(
        ArrayOfText(),
        nullable=False,
        default=list,
        comment="Array of URLs pointing to uploaded evidence files",
    )
    resolution_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    resolved_by_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    assigned_to_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Currently assigned moderator",
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    project: Mapped["Project"] = relationship(
        "Project", back_populates="disputes", lazy="selectin"
    )
    milestone: Mapped[Optional["Milestone"]] = relationship(
        "Milestone", back_populates="disputes", lazy="selectin"
    )
    raised_by: Mapped["User"] = relationship(
        "User", foreign_keys=[raised_by_id], back_populates="raised_disputes", lazy="selectin"
    )
    resolved_by: Mapped[Optional["User"]] = relationship(
        "User", foreign_keys=[resolved_by_id], back_populates="resolved_disputes", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Dispute id={self.id!r} project_id={self.project_id!r} "
            f"status={self.status.value!r}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# 6. transactions
# ══════════════════════════════════════════════════════════════════════════════


class Transaction(Base):
    """
    Immutable financial ledger. Records every money movement.
    No updated_at — transactions are append-only.

    metadata (JSONB) stores provider-specific raw response payloads
    (Razorpay order, payment, payout objects) for audit purposes.
    """

    __tablename__ = "transactions"
    __table_args__ = (
        Index("ix_transactions_project_type", "project_id", "transaction_type"),
        Index("ix_transactions_razorpay_ref", "razorpay_reference"),
        CheckConstraint("amount > 0", name="chk_positive_tx"),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    project_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("projects.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    milestone_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("milestones.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    transaction_type: Mapped[TransactionType] = mapped_column(
        SAEnum(TransactionType, native_enum=False, length=30),
        nullable=False,
        index=True,
    )
    amount: Mapped[int] = mapped_column(
        sa.BigInteger, nullable=False, comment="Always positive; direction from type; in paise"
    )
    razorpay_reference: Mapped[Optional[str]] = mapped_column(
        String(100), nullable=True
    )
    status: Mapped[TransactionStatus] = mapped_column(
        SAEnum(TransactionStatus, native_enum=False, length=20),
        nullable=False,
        default=TransactionStatus.pending,
        index=True,
    )
    tx_metadata: Mapped[dict] = mapped_column(
        JSONType(),
        nullable=False,
        default=dict,
        comment="Raw Razorpay response + any extra context",
    )
    previous_audit_hash: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,
        comment="Hash of the previous transaction in this project's audit chain",
    )
    audit_hash: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,
        index=True,
        comment="SHA-256 digest for append-only transaction verification",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    project: Mapped["Project"] = relationship(
        "Project", back_populates="transactions", lazy="selectin"
    )
    milestone: Mapped[Optional["Milestone"]] = relationship(
        "Milestone", back_populates="transactions", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Transaction id={self.id!r} type={self.transaction_type.value!r} "
            f"amount={self.amount} status={self.status.value!r}>"
        )


# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# 8. notifications
# ══════════════════════════════════════════════════════════════════════════════


class Notification(Base):
    """
    Outbound notification log.
    payload (JSONB) contains the rendered message body and any template params
    so the record is self-contained for debugging / retry.

    Example payload:
        {
          "template": "milestone_approved",
          "language": "en",
          "components": [{"type": "body", "parameters": [...]}],
          "message_id": "msg_xxx"
        }
    """

    __tablename__ = "notifications"
    __table_args__ = (
        Index("ix_notifications_user_type", "user_id", "type"),
        Index("ix_notifications_created", "created_at"),
        Index(
            "idx_notifications_unread",
            "user_id",
            "created_at",
            postgresql_where=text("sent_at IS NULL"),
        ),
    )

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    user_id: Mapped[str] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    type: Mapped[NotificationType] = mapped_column(
        SAEnum(NotificationType, native_enum=False, length=40),
        nullable=False,
        index=True,
    )
    channel: Mapped[NotificationChannel] = mapped_column(
        SAEnum(NotificationChannel, native_enum=False, length=20),
        nullable=False,
    )

    payload: Mapped[dict] = mapped_column(
        JSONType(),
        nullable=False,
        default=dict,
        comment="Rendered message body + provider-specific params",
    )

    sent_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    delivered_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Set via delivery webhook callback",
    )
    read_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Set when the dashboard user reads the notification",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    user: Mapped["User"] = relationship(
        "User", back_populates="notifications", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Notification id={self.id!r} user_id={self.user_id!r} "
            f"type={self.type.value!r} channel={self.channel.value!r}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# 9. public_submissions
# ══════════════════════════════════════════════════════════════════════════════


class PublicSubmission(TimestampMixin, Base):
    """
    Captures contact form messages and job applications from the public site.
    Payload (JSONB) dynamically holds fields based on type.
    """

    __tablename__ = "public_submissions"

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    submission_type: Mapped[SubmissionType] = mapped_column(
        SAEnum(SubmissionType, native_enum=False, length=20),
        nullable=False,
        index=True,
    )
    payload: Mapped[dict] = mapped_column(
        JSONType(),
        nullable=False,
        default=dict,
        comment="JSON record of form fields (name, email, message, etc.)",
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default=text("'pending'"),
        comment="'pending', 'reviewed', or 'archived'",
    )

    def __repr__(self) -> str:
        return (
            f"<PublicSubmission id={self.id!r} type={self.submission_type.value!r} "
            f"status={self.status!r}>"
        )


# ══════════════════════════════════════════════════════════════════════════════
# 10. system_settings
# ══════════════════════════════════════════════════════════════════════════════


class SystemSettings(TimestampMixin, Base):
    """
    Global platform configuration variables.
    Intended to be a singleton table (only 1 row ever).
    """

    __tablename__ = "system_settings"

    id: Mapped[str] = mapped_column(
        String(50),
        primary_key=True,
        default="default",
    )
    escrow_fee_percent: Mapped[Decimal] = mapped_column(
        Numeric(5, 2), nullable=False, server_default=text("5.00")
    )
    maintenance_mode: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    auto_release_days: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("3")
    )
    allow_new_registrations: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )

    def __repr__(self) -> str:
        return f"<SystemSettings fee={self.escrow_fee_percent}% maint={self.maintenance_mode}>"


# ══════════════════════════════════════════════════════════════════════════════
# 11. audit_events
# ══════════════════════════════════════════════════════════════════════════════

class AuditEvent(TimestampMixin, Base):
    """
    Immutable log of sensitive operations (e.g. login, payment, dispute).
    Stored in a dedicated table for security auditing.
    """
    __tablename__ = "audit_events"

    id: Mapped[str] = mapped_column(
        GUID(),
        primary_key=True,
        default=lambda: str(__import__('uuid').uuid4()),
    )
    user_id: Mapped[Optional[str]] = mapped_column(
        GUID(),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    event_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    resource_type: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    resource_id: Mapped[Optional[str]] = mapped_column(GUID(), nullable=True)
    
    event_metadata: Mapped[dict] = mapped_column(
        "metadata",
        JSONType(),
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
    )
    ip_address: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    user_agent: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    user: Mapped[Optional["User"]] = relationship("User", lazy="selectin")

    def __repr__(self) -> str:
        return f"<AuditEvent type={self.event_type} user_id={self.user_id}>"


# ══════════════════════════════════════════════════════════════════════════════
# Public re-exports
# ══════════════════════════════════════════════════════════════════════════════

__all__ = [
    "Base",
    "TimestampMixin",
    # Enums
    "UserRole",
    "ProjectStatus",
    "MilestoneStatus",
    "DisputeStatus",
    "TransactionType",
    "TransactionStatus",
    "NotificationType",
    "NotificationChannel",
    # Models
    "User",
    "Project",
    "Milestone",
    "TrustScore",
    "Dispute",
    "Transaction",
    "Notification",
    "PublicSubmission",
    "SubmissionType",
    "SystemSettings",
    "AuditEvent",
]
