"""
StayVise Alembic script.py.mako template
"""
"""add_public_submissions

Revision ID: e298fb14d34b
Revises: 786fae9d6d78
Create Date: 2026-04-17 18:42:28.036890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'e298fb14d34b'
down_revision: Union[str, None] = '786fae9d6d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_submissions',
    sa.Column('id', app.db.compat.GUID(), nullable=False),
    sa.Column('submission_type', sa.Enum('contact', 'career', 'general', name='submissiontype', native_enum=False, length=20), nullable=False),
    sa.Column('payload', app.db.compat.JSONType(), nullable=False, comment='JSON record of form fields (name, email, message, etc.)'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment="'pending', 'reviewed', or 'archived'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_submissions_submission_type'), 'public_submissions', ['submission_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_submissions_submission_type'), table_name='public_submissions')
    op.drop_table('public_submissions')
    # ### end Alembic commands ###
