"""
StayVise Alembic script.py.mako template
"""
"""Add SystemSettings table

Revision ID: 520ec8de2605
Revises: e298fb14d34b
Create Date: 2026-04-17 19:25:43.497299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520ec8de2605'
down_revision: Union[str, None] = 'e298fb14d34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('escrow_fee_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('5.00'), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_release_days', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('allow_new_registrations', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
