"""
StayVise Alembic script.py.mako template
"""
"""Add razorpay fields to users

Revision ID: 977e9516e39e
Revises: 0001
Create Date: 2026-04-13 21:14:44.813114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '977e9516e39e'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disputes', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('disputes', 'evidence_urls',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               comment='Array of URLs pointing to uploaded evidence files',
               existing_nullable=False)
    op.alter_column('milestones', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('milestones', 'razorpay_payout_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Razorpay Payout ID after funds released',
               existing_nullable=True)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='Rendered message body + provider-specific params',
               existing_nullable=False)
    op.alter_column('notifications', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Set via WhatsApp delivery webhook',
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='In paise? No — stored in INR.',
               existing_nullable=False)
    op.alter_column('projects', 'auto_release_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Set when last milestone submitted; funds release if client silent',
               existing_nullable=True)
    op.alter_column('projects', 'whatsapp_thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment="Meta conversation ID for this project's thread",
               existing_nullable=True)
    op.drop_constraint(op.f('projects_razorpay_order_id_key'), 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_razorpay_order_id'), table_name='projects')
    op.create_index(op.f('ix_projects_razorpay_order_id'), 'projects', ['razorpay_order_id'], unique=True)
    op.add_column('transactions', sa.Column('tx_metadata', app.db.compat.JSONType(), nullable=False, comment='Raw Razorpay response + any extra context'))
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Always positive; direction from type',
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.drop_column('transactions', 'metadata')
    op.alter_column('trust_scores', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trust_scores', 'avg_delivery_days',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment='Average days from project start to completion',
               existing_nullable=True)
    op.alter_column('trust_scores', 'response_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='% of WhatsApp messages responded to within 24h',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.add_column('users', sa.Column('razorpay_contact_id', sa.String(length=100), nullable=True, comment='RazorpayX Contact ID for this user'))
    op.add_column('users', sa.Column('razorpay_fund_account_id', sa.String(length=100), nullable=True, comment='RazorpayX Fund Account ID (bank/UPI) for payouts'))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='E.164 format, e.g. +919876543210',
               existing_comment='E.164 format',
               existing_nullable=False)
    op.alter_column('users', 'whatsapp_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name pulled from WhatsApp profile',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash; NULL for OTP-only users',
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.alter_column('whatsapp_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('whatsapp_sessions', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='E.164 format',
               existing_nullable=False)
    op.alter_column('whatsapp_sessions', 'user_id',
               existing_type=sa.UUID(),
               comment='NULL when user not yet onboarded',
               existing_nullable=True)
    op.alter_column('whatsapp_sessions', 'session_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('whatsapp_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Sessions expire after 24h of inactivity',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Sessions expire after 24h of inactivity',
               existing_nullable=False)
    op.alter_column('whatsapp_sessions', 'session_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('whatsapp_sessions', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='NULL when user not yet onboarded',
               existing_nullable=True)
    op.alter_column('whatsapp_sessions', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='E.164 format',
               existing_nullable=False)
    op.alter_column('whatsapp_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'])
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hash; NULL for OTP-only users',
               existing_nullable=True)
    op.alter_column('users', 'whatsapp_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name pulled from WhatsApp profile',
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               comment='E.164 format',
               existing_comment='E.164 format, e.g. +919876543210',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('users', 'razorpay_fund_account_id')
    op.drop_column('users', 'razorpay_contact_id')
    op.alter_column('trust_scores', 'response_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='% of WhatsApp messages responded to within 24h',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('trust_scores', 'avg_delivery_days',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='Average days from project start to completion',
               existing_nullable=True)
    op.alter_column('trust_scores', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['transaction_type'], unique=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Always positive; direction from type',
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('transactions', 'tx_metadata')
    op.drop_index(op.f('ix_projects_razorpay_order_id'), table_name='projects')
    op.create_index(op.f('ix_projects_razorpay_order_id'), 'projects', ['razorpay_order_id'], unique=False)
    op.create_unique_constraint(op.f('projects_razorpay_order_id_key'), 'projects', ['razorpay_order_id'])
    op.alter_column('projects', 'whatsapp_thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Meta conversation ID for this project's thread",
               existing_nullable=True)
    op.alter_column('projects', 'auto_release_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Set when last milestone submitted; funds release if client silent',
               existing_nullable=True)
    op.alter_column('projects', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='In paise? No — stored in INR.',
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('notifications', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Set via WhatsApp delivery webhook',
               existing_nullable=True)
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               comment=None,
               existing_comment='Rendered message body + provider-specific params',
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('milestones', 'razorpay_payout_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Razorpay Payout ID after funds released',
               existing_nullable=True)
    op.alter_column('milestones', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('disputes', 'evidence_urls',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               comment=None,
               existing_comment='Array of URLs pointing to uploaded evidence files',
               existing_nullable=False)
    op.alter_column('disputes', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
