"""
StayVise Alembic script.py.mako template
"""
"""Add razorpay_subscription_id to User

Revision ID: 786fae9d6d78
Revises: c2e8f7b6a901
Create Date: 2026-04-17 00:56:32.553834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '786fae9d6d78'
down_revision: Union[str, None] = 'c2e8f7b6a901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Set when the dashboard user reads the notification',
               existing_nullable=True)
    op.alter_column('proposals', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.alter_column('transactions', 'previous_audit_hash',
               existing_type=sa.VARCHAR(length=64),
               comment="Hash of the previous transaction in this project's audit chain",
               existing_nullable=True)
    op.alter_column('transactions', 'audit_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 digest for append-only transaction verification',
               existing_nullable=True)
    op.add_column('users', sa.Column('razorpay_subscription_id', sa.String(length=100), nullable=True, comment='Razorpay Subscription ID for Pro plan billing'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               comment='Profile photo URL or local data URI for dashboard/public profile',
               existing_nullable=True)
    op.alter_column('users', 'payout_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Masked payout configuration shown in dashboard settings',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'payout_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Masked payout configuration shown in dashboard settings',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Profile photo URL or local data URI for dashboard/public profile',
               existing_nullable=True)
    op.drop_column('users', 'razorpay_subscription_id')
    op.alter_column('transactions', 'audit_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 digest for append-only transaction verification',
               existing_nullable=True)
    op.alter_column('transactions', 'previous_audit_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment="Hash of the previous transaction in this project's audit chain",
               existing_nullable=True)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.alter_column('proposals', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Set when the dashboard user reads the notification',
               existing_nullable=True)
    # ### end Alembic commands ###
