"""
StayVise Alembic script.py.mako template
"""
"""Add username and other missing fields to users

Revision ID: cdea34971218
Revises: 977e9516e39e
Create Date: 2026-04-14 22:11:24.499624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'cdea34971218'
down_revision: Union[str, None] = '977e9516e39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', app.db.compat.GUID(), nullable=False),
    sa.Column('user_id', app.db.compat.GUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='Opaque identifier mapping to JWT jti or random ID'),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.add_column('disputes', sa.Column('assigned_to_id', app.db.compat.GUID(), nullable=True, comment='Currently assigned moderator'))
    op.create_foreign_key(None, 'disputes', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True, comment='Public vanity URL slug, e.g. stayvise.in/p/username'))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True, comment='Short biography / What I do (Markdown supported)'))
    op.add_column('users', sa.Column('notification_prefs', app.db.compat.JSONType(), server_default=sa.text("'{}'"), nullable=False, comment='JSON record of notification toggles'))
    op.add_column('users', sa.Column('billing_plan', sa.String(length=20), server_default=sa.text("'free'"), nullable=False, comment="'free' or 'pro'"))
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'subscription_expires_at')
    op.drop_column('users', 'billing_plan')
    op.drop_column('users', 'notification_prefs')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_column('disputes', 'assigned_to_id')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
