"""
StayVise Alembic script.py.mako template
"""
"""make_phone_nullable

Revision ID: 87f212b8b56d
Revises: 520ec8de2605
Create Date: 2026-04-18 11:26:43.721080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f212b8b56d'
down_revision: Union[str, None] = '520ec8de2605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='E.164 format, e.g. +919876543210. Null for magic link users until verified.',
               existing_comment='E.164 format, e.g. +919876543210')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='E.164 format, e.g. +919876543210',
               existing_comment='E.164 format, e.g. +919876543210. Null for magic link users until verified.')
    # ### end Alembic commands ###
